=== apache/cayenne/cayenne/src/main/resources/org/apache/cayenne/schema/14/dataMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~  or more contributor license agreements.  See the NOTICE file
  ~  distributed with this work for additional information
  ~  regarding copyright ownership.  The ASF licenses this file
  ~  to you under the Apache License, Version 2.0 (the
  ~  "License"); you may not use this file except in compliance
  ~  with the License.  You may obtain a copy of the License at
  ~
  ~    https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing,
  ~  software distributed under the License is distributed on an
  ~  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~  KIND, either express or implied.  See the License for the
  ~  specific language governing permissions and limitations
  ~  under the License.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<!--
	Cayenne entity map schema
	Defines format of Cayenne DataMap XML files (*.map.xml).  DataMap files contain
	the metadata needed for Cayenne object-relational features. Multiple DataMaps
	are usually combined in one shared namespace, so the elements of the DataMap
	may reference objects from other DataMaps.
-->
<xs:schema targetNamespace="http://cayenne.apache.org/schema/14/dataMap"
	xmlns:cay="http://cayenne.apache.org/schema/14/dataMap"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="14">
	<xs:element name="dataMap">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:property"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:embeddable"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:procedure"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:dbEntity"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:objEntity"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:dbRelationship"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:objRelationship"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="cay:objectQuery"/>
					<xs:element ref="cay:sqlQuery"/>
					<xs:element ref="cay:procedureQuery"/>
				</xs:choice>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dbEntity">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="cay:dbAttribute"/>
				<xs:element minOccurs="0" ref="cay:dbKeyGenerator"/>

				<!-- Qualifier for DB Entity -->
				<xs:element minOccurs="0" ref="cay:qualifier"/>

				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="schema" type="xs:string"/>
			<xs:attribute name="catalog" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dbAttribute">
		<xs:annotation>
			<xs:documentation>A database column.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="mandatory" type="xs:boolean"/>
			<xs:attribute name="primaryKey" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>If true, the value of attribute is unique and used as a primary key identifier.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="generated" type="xs:boolean"/>
			<xs:attribute name="length" type="xs:integer"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="scale" type="xs:integer"/>
			<xs:attribute name="type" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="objEntity">
		<xs:annotation>
			<xs:documentation>A persistent Java class managed by Cayenne.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:qualifier"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:embeddedAttribute"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:objAttribute"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:attributeOverride"/>

				<!--  Callbacks -->
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postAdd"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:prePersist"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postPersist"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:preUpdate"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postUpdate"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:preRemove"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postRemove"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postLoad"/>

				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="className" type="xs:string"/>
			<xs:attribute name="abstract" type="xs:boolean"/>
			<xs:attribute name="readOnly" type="xs:boolean"/>
			<xs:attribute name="dbEntityName" type="xs:string"/>
			<xs:attribute name="lockType" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="superClassName" type="xs:string"/>
			<xs:attribute name="superEntityName" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="qualifier" type="xs:string"/>

	<xs:element name="objAttribute">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="dbAttributePath" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="lazy" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="attributeOverride">
		<xs:complexType>
			<xs:attribute name="dbAttributePath" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="type" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="dbRelationship">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="cay:dbAttributePair"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
			<xs:attribute name="toDependentPK" type="xs:boolean"/>
			<xs:attribute name="toMany" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dbAttributePair">
		<xs:complexType>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="objRelationship">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="dbRelationshipPath" use="required" type="xs:string"/>
			<xs:attribute name="deleteRule" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
			<xs:attribute name="collectionType" type="xs:string"/>
			<xs:attribute name="mapKey" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="objectQuery">
		<xs:annotation>
			<xs:documentation>A named selecting query expressed in terms of object model using Cayenne QL.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:ql"/>
				<xs:element minOccurs="0" ref="cay:cacheGroup"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attributeGroup ref="cay:querySettings"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="sqlQuery">
		<xs:annotation>
			<xs:documentation>A named query expressed in SQL terms</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:sql"/>
				<xs:element minOccurs="0" ref="cay:cacheGroup"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:prefetch"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="root" type="xs:string"/>
			<xs:attribute name="rootName" type="xs:string"/>
			<xs:attributeGroup ref="cay:querySettings"/>
			<xs:attribute name="columnNameCapitalization" type="cay:columnNameCapitalization"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="procedureQuery">
		<xs:annotation>
			<xs:documentation>A named query that calls a stored procedure.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:cacheGroup"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="root" type="xs:string"/>
			<xs:attribute name="rootName" type="xs:string"/>
			<xs:attribute name="resultEntity" type="xs:string"/>
			<xs:attributeGroup ref="cay:querySettings"/>
			<xs:attribute name="fetchLimit" type="xs:nonNegativeInteger">
				<xs:annotation>
					<xs:documentation>A max number of rows fetched by a query.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="fetchOffset" type="xs:nonNegativeInteger">
				<xs:annotation>
					<xs:documentation>A number of rows skipped at the start of a query result.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="columnNameCapitalization" type="cay:columnNameCapitalization"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="cacheGroup" type="xs:string">
		<xs:annotation>
			<xs:documentation>A name of the cache group of a query used for cache configuration and invalidation purposes.</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:attributeGroup name="querySettings">
		<xs:attribute name="cacheStrategy">
			<xs:annotation>
				<xs:documentation>An optional cache strategy of a query.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="NO_CACHE"/>
					<xs:enumeration value="LOCAL_CACHE"/>
					<xs:enumeration value="LOCAL_CACHE_REFRESH"/>
					<xs:enumeration value="SHARED_CACHE"/>
					<xs:enumeration value="SHARED_CACHE_REFRESH"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="dataRows" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>Defines whether a query fetches DataRows instead of persistent objects.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="pageSize" type="xs:nonNegativeInteger">
			<xs:annotation>
				<xs:documentation>A page size of a query with a paginated result.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="statementFetchSize" type="xs:nonNegativeInteger">
			<xs:annotation>
				<xs:documentation>A fetch size of the JDBC statement of a query.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>

	<xs:simpleType name="columnNameCapitalization">
		<xs:annotation>
			<xs:documentation>A capitalization of the column names in a query result.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="DEFAULT"/>
			<xs:enumeration value="UPPER"/>
			<xs:enumeration value="LOWER"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="ql" type="xs:string">
		<xs:annotation>
			<xs:documentation>The query String of an "objectQuery" in the syntax of ObjectSelect.parse(..).</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="prefetch">
		<xs:annotation>
			<xs:documentation>A prefetch of a "sqlQuery" query.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="sql">
		<xs:annotation>
			<xs:documentation>Defines a SQL statement. Statements can be customized for different SQL dialects per DbAdapter class. If no adapter-specific statement is found, the one with no adapter label is used by default.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="adapterClass" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>A generic property of a DataMap.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="value" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="embeddable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="embeddableAttribute" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" use="required" type="xs:string"/>
						<xs:attribute name="type" use="required" type="xs:string"/>
						<xs:attribute name="dbAttributeName" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="className" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="embeddedAttribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded"
					ref="cay:embeddableAttributeOverride"/>
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="embeddableAttributeOverride">
		<xs:complexType>
			<xs:attribute name="dbAttributePath" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="procedure">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="procedureParameter">
					<xs:complexType>
						<xs:attribute name="name" use="required" type="xs:string"/>
						<xs:attribute name="type" use="required" type="xs:string"/>
						<xs:attribute name="length" type="xs:integer"/>
						<xs:attribute name="direction" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="schema" type="xs:string"/>
			<xs:attribute name="catalog" type="xs:string"/>
			<xs:attribute name="returningValue" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="preUpdate">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postPersist">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postUpdate">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postAdd">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="prePersist">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postRemove">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postLoad">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="preRemove">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="dbKeyGenerator">
		<xs:annotation>
			<xs:documentation>Used to install the Automatic Sequence/Key Generation facility for dbEntity. This feature is intended for use with simple (non-compound) integral primary keys.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dbGeneratorType" type="xs:string">
					<xs:annotation>
						<xs:documentation>Specifies the Key Generation Method that will be employed
      'ORACLE'               - use Oracle's SEQUENCE
      'NAMED_SEQUENCE_TABLE' - use USER designated SEQUENCE TABLE. User specifies the name of a DBMS Table with the schema (sequence INT) which will be used to hold sequence values (not supported yet)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element minOccurs="0" name="dbGeneratorName" type="xs:string">
					<xs:annotation>
						<xs:documentation>For dbGeneratorType ORACLE this is the name of the ORACLE SEQUENCE to use. The SEQUENCE is assumed to already exist in the Database.
If this is dbGeneratorType NAMED_SEQUENCE_TABLE Key Generation, this specifies the name of the SEQUENCE TABLE to use. The NAMED_SEQUENCE_TABLE is assumed to already exist in the database.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element minOccurs="0" name="dbKeyCacheSize" type="xs:integer">
					<xs:annotation>
						<xs:documentation>Size of key cache. For dbGeneratorType ORACLE , this value MUST match the Oracle SEQUENCE  INCREMENT value.  If there is a mismatch between this value and the Oracle SEQUENCE INCREMENT value, then there will likely be duplicate key problems.
For dbGeneratorType NAMED_SEQUENCE_TABLE , this tells how many keys the Container will fetch in a single DBMS call.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== apache/cayenne/cayenne/src/test/resources/relationships-to-many-fk.map.xml
<?xml version="1.0" encoding="utf-8"?>
<dataMap xmlns="http://cayenne.apache.org/schema/15/dataMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/15/dataMap https://cayenne.apache.org/schema/15/dataMap.xsd"
	 defaultPackage="org.apache.cayenne.testdo.relationships_to_many_fk">
	<dbEntity name="TO_MANY_FKDEP">
		<dbAttribute name="DEP_ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="NAME" type="VARCHAR" length="200"/>
		<dbAttribute name="OTHER_ID" type="INTEGER" primaryKey="true" mandatory="true"/>
	</dbEntity>
	<dbEntity name="TO_MANY_FKROOT">
		<dbAttribute name="FK_ID" type="INTEGER"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="NAME" type="VARCHAR" length="100"/>
	</dbEntity>
	<dbEntity name="TO_MANY_ROOT2">
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="NAME" type="VARCHAR" length="100"/>
	</dbEntity>
	<objEntity name="ToManyFkDep" className="org.apache.cayenne.testdo.relationships_to_many_fk.ToManyFkDep" dbEntityName="TO_MANY_FKDEP">
		<objAttribute name="depId" type="java.lang.Integer" dbAttributePath="DEP_ID"/>
		<objAttribute name="name" type="java.lang.String" dbAttributePath="NAME"/>
	</objEntity>
	<objEntity name="ToManyFkRoot" className="org.apache.cayenne.testdo.relationships_to_many_fk.ToManyFkRoot" dbEntityName="TO_MANY_FKROOT">
		<objAttribute name="depId" type="java.lang.Integer" dbAttributePath="FK_ID"/>
		<objAttribute name="name" type="java.lang.String" dbAttributePath="NAME"/>
	</objEntity>
	<objEntity name="ToManyRoot2" className="org.apache.cayenne.testdo.relationships_to_many_fk.ToManyRoot2" dbEntityName="TO_MANY_ROOT2">
		<objAttribute name="name" type="java.lang.String" dbAttributePath="NAME"/>
	</objEntity>
	<dbRelationship name="root" source="TO_MANY_FKDEP" target="TO_MANY_FKROOT">
		<dbAttributePair source="DEP_ID" target="FK_ID"/>
	</dbRelationship>
	<dbRelationship name="root2" source="TO_MANY_FKDEP" target="TO_MANY_ROOT2" foreignKey="true">
		<dbAttributePair source="OTHER_ID" target="ID"/>
	</dbRelationship>
	<dbRelationship name="deps" source="TO_MANY_FKROOT" target="TO_MANY_FKDEP" toMany="true">
		<dbAttributePair source="FK_ID" target="DEP_ID"/>
	</dbRelationship>
	<dbRelationship name="deps" source="TO_MANY_ROOT2" target="TO_MANY_FKDEP" toMany="true">
		<dbAttributePair source="ID" target="OTHER_ID"/>
	</dbRelationship>
	<objRelationship name="root" source="ToManyFkDep" target="ToManyFkRoot" dbRelationshipPath="root"/>
	<objRelationship name="root2" source="ToManyFkDep" target="ToManyRoot2" dbRelationshipPath="root2"/>
	<objRelationship name="deps" source="ToManyFkRoot" target="ToManyFkDep" dbRelationshipPath="deps"/>
	<objRelationship name="deps" source="ToManyRoot2" target="ToManyFkDep" dbRelationshipPath="deps"/>
</dataMap>

=== apache/cayenne/cayenne-crypto/src/test/resources/datamap.map.xml
<?xml version="1.0" encoding="utf-8"?>
<dataMap xmlns="http://cayenne.apache.org/schema/15/dataMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/15/dataMap https://cayenne.apache.org/schema/15/dataMap.xsd"
	 defaultPackage="org.apache.cayenne.crypto.db">
	<dbEntity name="TABLE1">
		<dbAttribute name="CRYPTO_INT" type="BLOB"/>
		<dbAttribute name="CRYPTO_STRING" type="CLOB"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="PLAIN_INT" type="INTEGER"/>
		<dbAttribute name="PLAIN_STRING" type="VARCHAR" length="200"/>
	</dbEntity>
	<dbEntity name="TABLE2">
		<dbAttribute name="CRYPTO_BYTES" type="BLOB"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="PLAIN_BYTES" type="LONGVARBINARY"/>
	</dbEntity>
	<dbEntity name="TABLE3">
		<dbAttribute name="CRYPTO_BYTES" type="LONGVARBINARY"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
	</dbEntity>
	<dbEntity name="TABLE4">
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="PLAIN_INT" type="INTEGER"/>
		<dbAttribute name="PLAIN_STRING" type="VARCHAR" length="200"/>
	</dbEntity>
	<dbEntity name="TABLE5">
		<dbAttribute name="CRYPTO_INT1" type="CLOB"/>
		<dbAttribute name="CRYPTO_INT2" type="BLOB"/>
		<dbAttribute name="CRYPTO_INT3" type="VARBINARY" length="255"/>
		<dbAttribute name="CRYPTO_INT4" type="BLOB"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
	</dbEntity>
	<dbEntity name="TABLE7">
		<dbAttribute name="CRYPTO_INT" type="BLOB"/>
		<dbAttribute name="CRYPTO_STRING" type="CLOB"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="TABLE1_ID" type="INTEGER"/>
	</dbEntity>
	<dbEntity name="TABLE8">
		<dbAttribute name="CRYPTO_BYTES" type="LONGVARBINARY"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
	</dbEntity>
	<objEntity name="Table1" className="org.apache.cayenne.crypto.db.Table1" dbEntityName="TABLE1">
		<objAttribute name="cryptoInt" type="int" dbAttributePath="CRYPTO_INT"/>
		<objAttribute name="cryptoString" type="java.lang.String" dbAttributePath="CRYPTO_STRING"/>
		<objAttribute name="plainInt" type="int" dbAttributePath="PLAIN_INT"/>
		<objAttribute name="plainString" type="java.lang.String" dbAttributePath="PLAIN_STRING"/>
	</objEntity>
	<objEntity name="Table2" className="org.apache.cayenne.crypto.db.Table2" dbEntityName="TABLE2">
		<objAttribute name="cryptoBytes" type="byte[]" dbAttributePath="CRYPTO_BYTES"/>
		<objAttribute name="plainBytes" type="byte[]" dbAttributePath="PLAIN_BYTES"/>
	</objEntity>
	<objEntity name="Table3" className="org.apache.cayenne.crypto.db.Table3" dbEntityName="TABLE3">
		<objAttribute name="cryptoString" type="java.lang.String" dbAttributePath="CRYPTO_BYTES"/>
	</objEntity>
	<objEntity name="Table4" className="org.apache.cayenne.crypto.db.Table4" dbEntityName="TABLE4">
		<objAttribute name="plainInt" type="int" dbAttributePath="PLAIN_INT"/>
		<objAttribute name="plainString" type="java.lang.String" dbAttributePath="PLAIN_STRING"/>
	</objEntity>
	<objEntity name="Table5" className="org.apache.cayenne.crypto.db.Table5" dbEntityName="TABLE5">
		<objAttribute name="cryptoInt1" type="int" dbAttributePath="CRYPTO_INT1"/>
		<objAttribute name="cryptoInt3" type="int" dbAttributePath="CRYPTO_INT3"/>
		<objAttribute name="cryptoInt4" type="int" dbAttributePath="CRYPTO_INT4"/>
	</objEntity>
	<objEntity name="Table6" className="org.apache.cayenne.crypto.db.Table6" dbEntityName="TABLE5">
		<objAttribute name="cryptoInt1" type="long" dbAttributePath="CRYPTO_INT1"/>
		<objAttribute name="cryptoInt4" type="int" dbAttributePath="CRYPTO_INT4"/>
	</objEntity>
	<objEntity name="Table7" className="org.apache.cayenne.crypto.db.Table7" dbEntityName="TABLE7">
		<objAttribute name="cryptoInt" type="int" dbAttributePath="CRYPTO_INT"/>
		<objAttribute name="cryptoString" type="java.lang.String" dbAttributePath="CRYPTO_STRING"/>
	</objEntity>
	<objEntity name="Table8" className="org.apache.cayenne.crypto.db.Table8" lockType="optimistic" dbEntityName="TABLE8">
		<objAttribute name="cryptoString" type="java.lang.String" lock="true" dbAttributePath="CRYPTO_BYTES"/>
	</objEntity>
	<dbRelationship name="table7s" source="TABLE1" target="TABLE7" toMany="true">
		<dbAttributePair source="ID" target="TABLE1_ID"/>
	</dbRelationship>
	<dbRelationship name="toTable1" source="TABLE7" target="TABLE1" foreignKey="true">
		<dbAttributePair source="TABLE1_ID" target="ID"/>
	</dbRelationship>
	<objRelationship name="table7s" source="Table1" target="Table7" deleteRule="deny" dbRelationshipPath="table7s"/>
	<objRelationship name="toTable1" source="Table7" target="Table1" deleteRule="nullify" dbRelationshipPath="toTable1"/>
</dataMap>

=== apache/cayenne/cayenne/src/test/resources/relationships-collection-to-many.map.xml
<?xml version="1.0" encoding="utf-8"?>
<dataMap xmlns="http://cayenne.apache.org/schema/15/dataMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/15/dataMap https://cayenne.apache.org/schema/15/dataMap.xsd"
	 defaultPackage="org.apache.cayenne.testdo.relationships_collection_to_many">
	<dbEntity name="COLLECTION_TO_MANY">
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
	</dbEntity>
	<dbEntity name="COLLECTION_TO_MANY_TARGET">
		<dbAttribute name="COLLECTION_TO_MANY_ID" type="INTEGER"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
	</dbEntity>
	<objEntity name="CollectionToMany" className="org.apache.cayenne.testdo.relationships_collection_to_many.CollectionToMany" dbEntityName="COLLECTION_TO_MANY"/>
	<objEntity name="CollectionToManyTarget" className="org.apache.cayenne.testdo.relationships_collection_to_many.CollectionToManyTarget" dbEntityName="COLLECTION_TO_MANY_TARGET"/>
	<dbRelationship name="targets" source="COLLECTION_TO_MANY" target="COLLECTION_TO_MANY_TARGET" toMany="true">
		<dbAttributePair source="ID" target="COLLECTION_TO_MANY_ID"/>
	</dbRelationship>
	<dbRelationship name="collectionToMany" source="COLLECTION_TO_MANY_TARGET" target="COLLECTION_TO_MANY" foreignKey="true">
		<dbAttributePair source="COLLECTION_TO_MANY_ID" target="ID"/>
	</dbRelationship>
	<objRelationship name="targets" source="CollectionToMany" target="CollectionToManyTarget" collectionType="java.util.Collection" dbRelationshipPath="targets"/>
	<objRelationship name="collectionToMany" source="CollectionToManyTarget" target="CollectionToMany" dbRelationshipPath="collectionToMany"/>
</dataMap>
