=== apache/cayenne/cayenne/src/main/resources/org/apache/cayenne/schema/14/dataMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~  or more contributor license agreements.  See the NOTICE file
  ~  distributed with this work for additional information
  ~  regarding copyright ownership.  The ASF licenses this file
  ~  to you under the Apache License, Version 2.0 (the
  ~  "License"); you may not use this file except in compliance
  ~  with the License.  You may obtain a copy of the License at
  ~
  ~    https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing,
  ~  software distributed under the License is distributed on an
  ~  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~  KIND, either express or implied.  See the License for the
  ~  specific language governing permissions and limitations
  ~  under the License.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<!--
	Cayenne entity map schema
	Defines format of Cayenne DataMap XML files (*.map.xml).  DataMap files contain
	the metadata needed for Cayenne object-relational features. Multiple DataMaps
	are usually combined in one shared namespace, so the elements of the DataMap
	may reference objects from other DataMaps.
-->
<xs:schema targetNamespace="http://cayenne.apache.org/schema/14/dataMap"
	xmlns:cay="http://cayenne.apache.org/schema/14/dataMap"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="14">
	<xs:element name="dataMap">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:property"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:embeddable"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:procedure"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:dbEntity"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:objEntity"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:dbRelationship"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:objRelationship"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="cay:objectQuery"/>
					<xs:element ref="cay:sqlQuery"/>
					<xs:element ref="cay:procedureQuery"/>
				</xs:choice>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dbEntity">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="cay:dbAttribute"/>
				<xs:element minOccurs="0" ref="cay:dbKeyGenerator"/>

				<!-- Qualifier for DB Entity -->
				<xs:element minOccurs="0" ref="cay:qualifier"/>

				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="schema" type="xs:string"/>
			<xs:attribute name="catalog" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dbAttribute">
		<xs:annotation>
			<xs:documentation>A database column.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="mandatory" type="xs:boolean"/>
			<xs:attribute name="primaryKey" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>If true, the value of attribute is unique and used as a primary key identifier.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="generated" type="xs:boolean"/>
			<xs:attribute name="length" type="xs:integer"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="scale" type="xs:integer"/>
			<xs:attribute name="type" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="objEntity">
		<xs:annotation>
			<xs:documentation>A persistent Java class managed by Cayenne.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:qualifier"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:embeddedAttribute"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:objAttribute"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:attributeOverride"/>

				<!--  Callbacks -->
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postAdd"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:prePersist"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postPersist"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:preUpdate"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postUpdate"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:preRemove"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postRemove"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postLoad"/>

				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="className" type="xs:string"/>
			<xs:attribute name="abstract" type="xs:boolean"/>
			<xs:attribute name="readOnly" type="xs:boolean"/>
			<xs:attribute name="dbEntityName" type="xs:string"/>
			<xs:attribute name="lockType" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="superClassName" type="xs:string"/>
			<xs:attribute name="superEntityName" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="qualifier" type="xs:string"/>

	<xs:element name="objAttribute">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="dbAttributePath" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="lazy" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="attributeOverride">
		<xs:complexType>
			<xs:attribute name="dbAttributePath" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="type" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="dbRelationship">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="cay:dbAttributePair"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
			<xs:attribute name="toDependentPK" type="xs:boolean"/>
			<xs:attribute name="toMany" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dbAttributePair">
		<xs:complexType>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="objRelationship">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="dbRelationshipPath" use="required" type="xs:string"/>
			<xs:attribute name="deleteRule" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
			<xs:attribute name="collectionType" type="xs:string"/>
			<xs:attribute name="mapKey" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="objectQuery">
		<xs:annotation>
			<xs:documentation>A named selecting query expressed in terms of object model using Cayenne QL.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:ql"/>
				<xs:element minOccurs="0" ref="cay:cacheGroup"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attributeGroup ref="cay:querySettings"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="sqlQuery">
		<xs:annotation>
			<xs:documentation>A named query expressed in SQL terms</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:sql"/>
				<xs:element minOccurs="0" ref="cay:cacheGroup"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:prefetch"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="root" type="xs:string"/>
			<xs:attribute name="rootName" type="xs:string"/>
			<xs:attributeGroup ref="cay:querySettings"/>
			<xs:attribute name="columnNameCapitalization" type="cay:columnNameCapitalization"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="procedureQuery">
		<xs:annotation>
			<xs:documentation>A named query that calls a stored procedure.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:cacheGroup"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="root" type="xs:string"/>
			<xs:attribute name="rootName" type="xs:string"/>
			<xs:attribute name="resultEntity" type="xs:string"/>
			<xs:attributeGroup ref="cay:querySettings"/>
			<xs:attribute name="fetchLimit" type="xs:nonNegativeInteger">
				<xs:annotation>
					<xs:documentation>A max number of rows fetched by a query.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="fetchOffset" type="xs:nonNegativeInteger">
				<xs:annotation>
					<xs:documentation>A number of rows skipped at the start of a query result.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="columnNameCapitalization" type="cay:columnNameCapitalization"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="cacheGroup" type="xs:string">
		<xs:annotation>
			<xs:documentation>A name of the cache group of a query used for cache configuration and invalidation purposes.</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:attributeGroup name="querySettings">
		<xs:attribute name="cacheStrategy">
			<xs:annotation>
				<xs:documentation>An optional cache strategy of a query.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="NO_CACHE"/>
					<xs:enumeration value="LOCAL_CACHE"/>
					<xs:enumeration value="LOCAL_CACHE_REFRESH"/>
					<xs:enumeration value="SHARED_CACHE"/>
					<xs:enumeration value="SHARED_CACHE_REFRESH"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="dataRows" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>Defines whether a query fetches DataRows instead of persistent objects.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="pageSize" type="xs:nonNegativeInteger">
			<xs:annotation>
				<xs:documentation>A page size of a query with a paginated result.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="statementFetchSize" type="xs:nonNegativeInteger">
			<xs:annotation>
				<xs:documentation>A fetch size of the JDBC statement of a query.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>

	<xs:simpleType name="columnNameCapitalization">
		<xs:annotation>
			<xs:documentation>A capitalization of the column names in a query result.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="DEFAULT"/>
			<xs:enumeration value="UPPER"/>
			<xs:enumeration value="LOWER"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="ql" type="xs:string">
		<xs:annotation>
			<xs:documentation>The query String of an "objectQuery" in the syntax of ObjectSelect.parse(..).</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="prefetch">
		<xs:annotation>
			<xs:documentation>A prefetch of a "sqlQuery" query.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="sql">
		<xs:annotation>
			<xs:documentation>Defines a SQL statement. Statements can be customized for different SQL dialects per DbAdapter class. If no adapter-specific statement is found, the one with no adapter label is used by default.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="adapterClass" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>A generic property of a DataMap.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="value" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="embeddable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="embeddableAttribute" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" use="required" type="xs:string"/>
						<xs:attribute name="type" use="required" type="xs:string"/>
						<xs:attribute name="dbAttributeName" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="className" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="embeddedAttribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded"
					ref="cay:embeddableAttributeOverride"/>
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="embeddableAttributeOverride">
		<xs:complexType>
			<xs:attribute name="dbAttributePath" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="procedure">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="procedureParameter">
					<xs:complexType>
						<xs:attribute name="name" use="required" type="xs:string"/>
						<xs:attribute name="type" use="required" type="xs:string"/>
						<xs:attribute name="length" type="xs:integer"/>
						<xs:attribute name="direction" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="schema" type="xs:string"/>
			<xs:attribute name="catalog" type="xs:string"/>
			<xs:attribute name="returningValue" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="preUpdate">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postPersist">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postUpdate">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postAdd">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="prePersist">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postRemove">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postLoad">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="preRemove">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="dbKeyGenerator">
		<xs:annotation>
			<xs:documentation>Used to install the Automatic Sequence/Key Generation facility for dbEntity. This feature is intended for use with simple (non-compound) integral primary keys.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dbGeneratorType" type="xs:string">
					<xs:annotation>
						<xs:documentation>Specifies the Key Generation Method that will be employed
      'ORACLE'               - use Oracle's SEQUENCE
      'NAMED_SEQUENCE_TABLE' - use USER designated SEQUENCE TABLE. User specifies the name of a DBMS Table with the schema (sequence INT) which will be used to hold sequence values (not supported yet)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element minOccurs="0" name="dbGeneratorName" type="xs:string">
					<xs:annotation>
						<xs:documentation>For dbGeneratorType ORACLE this is the name of the ORACLE SEQUENCE to use. The SEQUENCE is assumed to already exist in the Database.
If this is dbGeneratorType NAMED_SEQUENCE_TABLE Key Generation, this specifies the name of the SEQUENCE TABLE to use. The NAMED_SEQUENCE_TABLE is assumed to already exist in the database.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element minOccurs="0" name="dbKeyCacheSize" type="xs:integer">
					<xs:annotation>
						<xs:documentation>Size of key cache. For dbGeneratorType ORACLE , this value MUST match the Oracle SEQUENCE  INCREMENT value.  If there is a mismatch between this value and the Oracle SEQUENCE INCREMENT value, then there will likely be duplicate key problems.
For dbGeneratorType NAMED_SEQUENCE_TABLE , this tells how many keys the Container will fetch in a single DBMS call.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== apache/cayenne/cayenne/src/test/resources/qualified.map.xml
<?xml version="1.0" encoding="utf-8"?>
<dataMap xmlns="http://cayenne.apache.org/schema/15/dataMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/15/dataMap https://cayenne.apache.org/schema/15/dataMap.xsd"
	 defaultPackage="org.apache.cayenne.testdo.qualified"
	 quoteSqlIdentifiers="true">
	<dbEntity name="TEST_QUALIFIED1">
		<dbAttribute name="DELETED" type="BOOLEAN"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="NAME" type="VARCHAR" length="200"/>
	</dbEntity>
	<dbEntity name="TEST_QUALIFIED2">
		<dbAttribute name="DELETED" type="BOOLEAN"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="NAME" type="VARCHAR" length="200"/>
		<dbAttribute name="QUALIFIED1_ID" type="INTEGER"/>
	</dbEntity>
	<dbEntity name="TEST_QUALIFIED3">
		<dbAttribute name="DELETED" type="BOOLEAN"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="NAME" type="VARCHAR" length="200"/>
		<qualifier><![CDATA[DELETED = null]]></qualifier>
	</dbEntity>
	<dbEntity name="TEST_QUALIFIED4">
		<dbAttribute name="DELETED" type="BOOLEAN"/>
		<dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true"/>
		<dbAttribute name="NAME" type="VARCHAR" length="200"/>
		<dbAttribute name="QUALIFIED3_ID" type="INTEGER"/>
		<qualifier><![CDATA[DELETED = null]]></qualifier>
	</dbEntity>
	<objEntity name="Qualified1" className="org.apache.cayenne.testdo.qualified.Qualified1" dbEntityName="TEST_QUALIFIED1">
		<qualifier><![CDATA[deleted = null]]></qualifier>
		<objAttribute name="deleted" type="java.lang.Boolean" dbAttributePath="DELETED"/>
		<objAttribute name="name" type="java.lang.String" dbAttributePath="NAME"/>
	</objEntity>
	<objEntity name="Qualified2" className="org.apache.cayenne.testdo.qualified.Qualified2" dbEntityName="TEST_QUALIFIED2">
		<qualifier><![CDATA[deleted = null]]></qualifier>
		<objAttribute name="deleted" type="java.lang.Boolean" dbAttributePath="DELETED"/>
		<objAttribute name="name" type="java.lang.String" dbAttributePath="NAME"/>
	</objEntity>
	<objEntity name="Qualified3" className="org.apache.cayenne.testdo.qualified.Qualified3" dbEntityName="TEST_QUALIFIED3">
		<objAttribute name="name" type="java.lang.String" dbAttributePath="NAME"/>
	</objEntity>
	<objEntity name="Qualified4" className="org.apache.cayenne.testdo.qualified.Qualified4" dbEntityName="TEST_QUALIFIED4">
		<objAttribute name="name" type="java.lang.String" dbAttributePath="NAME"/>
	</objEntity>
	<dbRelationship name="qualified2s" source="TEST_QUALIFIED1" target="TEST_QUALIFIED2" toMany="true">
		<dbAttributePair source="ID" target="QUALIFIED1_ID"/>
	</dbRelationship>
	<dbRelationship name="qualified1" source="TEST_QUALIFIED2" target="TEST_QUALIFIED1" foreignKey="true">
		<dbAttributePair source="QUALIFIED1_ID" target="ID"/>
	</dbRelationship>
	<dbRelationship name="qualified4s" source="TEST_QUALIFIED3" target="TEST_QUALIFIED4" toMany="true">
		<dbAttributePair source="ID" target="QUALIFIED3_ID"/>
	</dbRelationship>
	<dbRelationship name="qualified3" source="TEST_QUALIFIED4" target="TEST_QUALIFIED3" foreignKey="true">
		<dbAttributePair source="QUALIFIED3_ID" target="ID"/>
	</dbRelationship>
	<objRelationship name="qualified2s" source="Qualified1" target="Qualified2" dbRelationshipPath="qualified2s"/>
	<objRelationship name="qualified1" source="Qualified2" target="Qualified1" dbRelationshipPath="qualified1"/>
	<objRelationship name="qualified4s" source="Qualified3" target="Qualified4" deleteRule="deny" dbRelationshipPath="qualified4s"/>
	<objRelationship name="qualified3" source="Qualified4" target="Qualified3" deleteRule="nullify" dbRelationshipPath="qualified3"/>
</dataMap>

=== apache/cayenne/cayenne-maven-plugin/src/test/resources/org/apache/cayenne/tools/dbimport/testDbAttributeChange.map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~  or more contributor license agreements.  See the NOTICE file
  ~  distributed with this work for additional information
  ~  regarding copyright ownership.  The ASF licenses this file
  ~  to you under the Apache License, Version 2.0 (the
  ~  "License"); you may not use this file except in compliance
  ~  with the License.  You may obtain a copy of the License at
  ~
  ~    https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing,
  ~  software distributed under the License is distributed on an
  ~  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~  KIND, either express or implied.  See the License for the
  ~  specific language governing permissions and limitations
  ~  under the License.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<dataMap xmlns="http://cayenne.apache.org/schema/15/dataMap"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://cayenne.apache.org/schema/15/dataMap http://cayenne.apache.org/schema/15/dataMap.xsd">

    <dbEntity name="parent" schema="SCHEMA_01">
        <dbAttribute name="COL2" type="CHAR" length="25"/>
        <dbAttribute name="COL3" type="DECIMAL" length="10" scale="2"/>
        <dbAttribute name="COL4" type="VARCHAR" length="25"/>
        <dbAttribute name="COL5" type="DATE" length="10"/>
        <dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true" length="10"/>
    </dbEntity>
    <dbEntity name="CHILD" schema="SCHEMA_01">
        <dbAttribute name="col1" type="INTEGER"/>
        <dbAttribute name="col2" type="DECIMAL" length="10" scale="2"/>
        <dbAttribute name="COL4" type="VARCHAR" length="25"/>
        <dbAttribute name="COL5" type="DATE" length="10"/>
        <dbAttribute name="ID" type="INTEGER" primaryKey="true" mandatory="true" length="10"/>
        <dbAttribute name="parent_id" type="CHAR" length="25"/>
    </dbEntity>
    <objEntity name="Child" className="Child" dbEntityName="CHILD">
        <objAttribute name="col3" type="java.math.BigDecimal" dbAttributePath="COL3"/>
        <objAttribute name="col4" type="java.lang.String" dbAttributePath="COL4"/>
        <objAttribute name="col5" type="java.util.Date" dbAttributePath="COL5"/>
        <objAttribute name="parentId" type="java.lang.String" dbAttributePath="PARENT_ID"/>
    </objEntity>
    <objEntity name="Parent" className="Parent" dbEntityName="parent">
        <objAttribute name="col2" type="java.lang.String" dbAttributePath="COL2"/>
        <objAttribute name="col3" type="java.math.BigDecimal" dbAttributePath="COL3"/>
        <objAttribute name="col4" type="java.lang.String" dbAttributePath="COL4"/>
        <objAttribute name="col5" type="java.util.Date" dbAttributePath="COL5"/>
    </objEntity>

    <dbRelationship name="parent" source="CHILD" target="parent" foreignKey="true">
        <dbAttributePair source="parent_id" target="ID"/>
    </dbRelationship>
    <dbRelationship name="children" source="parent" target="CHILD" toMany="true">
        <dbAttributePair source="ID" target="parent_id"/>
    </dbRelationship>

    <objRelationship name="parent" source="Child" target="Parent" deleteRule="nullify" dbRelationshipPath="parent"/>
    <objRelationship name="children" source="Parent" target="Child" deleteRule="deny" dbRelationshipPath="children"/>
</dataMap>

=== apache/cayenne/cayenne-maven-plugin/src/test/resources/org/apache/cayenne/tools/dbimport/testFkAttributeRename.map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~  or more contributor license agreements.  See the NOTICE file
  ~  distributed with this work for additional information
  ~  regarding copyright ownership.  The ASF licenses this file
  ~  to you under the Apache License, Version 2.0 (the
  ~  "License"); you may not use this file except in compliance
  ~  with the License.  You may obtain a copy of the License at
  ~
  ~    https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing,
  ~  software distributed under the License is distributed on an
  ~  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~  KIND, either express or implied.  See the License for the
  ~  specific language governing permissions and limitations
  ~  under the License.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<dataMap xmlns="http://cayenne.apache.org/schema/15/dataMap"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://cayenne.apache.org/schema/15/dataMap http://cayenne.apache.org/schema/15/dataMap.xsd">

    <dbEntity name="CHILD" schema="SCHEMA_01">
        <dbAttribute name="id" type="INTEGER" length="10"/>
        <dbAttribute name="parent_id" type="INTEGER" length="10"/>
    </dbEntity>
    <dbEntity name="PARENT" schema="SCHEMA_01">
        <dbAttribute name="id" type="INTEGER" primaryKey="true" mandatory="true" length="10"/>
    </dbEntity>
    <objEntity name="Child" className="Child" dbEntityName="CHILD">
    </objEntity>
    <objEntity name="Parent" className="Parent" dbEntityName="PARENT">
    </objEntity>
    <dbRelationship name="parent" source="CHILD" target="PARENT" foreignKey="true">
        <dbAttributePair source="parent_id" target="id"/>
    </dbRelationship>
    <dbRelationship name="children" source="PARENT" target="CHILD" toMany="true">
        <dbAttributePair source="id" target="parent_id"/>
    </dbRelationship>
    <objRelationship name="parent" source="Child" target="Parent" deleteRule="nullify" dbRelationshipPath="parent"/>
    <objRelationship name="children" source="Parent" target="Child" deleteRule="deny" dbRelationshipPath="children"/>
</dataMap>
