=== apache/cayenne/cayenne/src/main/resources/org/apache/cayenne/schema/14/project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~  or more contributor license agreements.  See the NOTICE file
  ~  distributed with this work for additional information
  ~  regarding copyright ownership.  The ASF licenses this file
  ~  to you under the Apache License, Version 2.0 (the
  ~  "License"); you may not use this file except in compliance
  ~  with the License.  You may obtain a copy of the License at
  ~
  ~    https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing,
  ~  software distributed under the License is distributed on an
  ~  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~  KIND, either express or implied.  See the License for the
  ~  specific language governing permissions and limitations
  ~  under the License.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<xs:schema targetNamespace="http://cayenne.apache.org/schema/14/project"
           elementFormDefault="qualified" version="14"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cay="http://cayenne.apache.org/schema/14/project">

    <xs:element name="project">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:map"/>
                <xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
            </xs:sequence>
            <xs:attribute name="sharedCache" type="xs:boolean" default="true">
                <xs:annotation>
                    <xs:documentation>Defines whether the object snapshots are cached in a cache shared between all ObjectContexts.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="validateOnCommit" type="xs:boolean" default="true">
                <xs:annotation>
                    <xs:documentation>Defines whether the objects are validated before they are committed.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="map">
        <xs:annotation>
            <xs:documentation>Link to an external file with data map.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="name" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== apache/cayenne/cayenne/src/test/resources/cayenne-ALL.xml
<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://cayenne.apache.org/schema/15/project"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/15/project https://cayenne.apache.org/schema/15/project.xsd">
	<map name="testmap"/>
	<map name="compound"/>
	<map name="misc-types"/>
	<map name="things"/>
	<map name="numeric-types"/>
	<map name="binary-pk"/>
	<map name="no-pk"/>
	<map name="lob"/>
	<map name="date-time"/>
	<map name="enum"/>
	<map name="json"/>
	<map name="extended-type"/>
	<map name="generated"/>
	<map name="mixed-persistence-strategy"/>
	<map name="people"/>
	<map name="primitive"/>
	<map name="inheritance"/>
	<map name="locking"/>
	<map name="soft-delete"/>
	<map name="empty"/>
	<map name="relationships"/>
	<map name="relationships-activity"/>
	<map name="relationships-delete-rules"/>
	<map name="relationships-collection-to-many"/>
	<map name="relationships-child-master"/>
	<map name="relationships-clob"/>
	<map name="relationships-flattened"/>
	<map name="relationships-many-to-many-join"/>
	<map name="relationships-set-to-many"/>
	<map name="relationships-to-many-fk"/>
	<map name="relationships-to-one-fk"/>
	<map name="return-types"/>
	<map name="uuid"/>
	<map name="multi-tier"/>
	<map name="reflexive"/>
	<map name="lifecycle-callbacks-order"/>
	<map name="map-to-many"/>
	<map name="meaningful-pk"/>
	<map name="table-primitives"/>
	<map name="generic"/>
	<map name="map-db1"/>
	<map name="map-db2"/>
	<map name="embeddable"/>
	<map name="qualified"/>
	<map name="quoted-identifiers"/>
	<map name="inheritance-single-table1"/>
	<map name="inheritance-vertical"/>
	<map name="oneway-rels"/>
	<map name="unsupported-distinct-types"/>
	<map name="array-type"/>
	<map name="cay-2032"/>
	<map name="weighted-sort"/>
	<map name="hybrid-data-object"/>
	<map name="legacy-date-time"/>
	<map name="inheritance-with-enum"/>
	<map name="lazy-attributes"/>
	<map name="cay2666/datamap"/>
	<map name="cay2641/datamapLazy"/>
	<map name="entity_callbacks/datamapEntityCallbacks"/>
</project>
